### PR TITLE
Added ability to cargo install

### PR DESCRIPTION
**Pull request by LemonjamesD**
you can `cargo install https://github.com/WaffleMixer/Rex.git` with these changes

### CODE REVIEW

**Comment by WaffleMixer** [comment]
Hey, thanks for the PR but I'm not sure if `cargo install` is valid here because the sqlite db is created on the current working directory. I haven't quite figured out/looked into how to work with this yet.

**Comment by LemonjamesD** [comment]
> Hey, thanks for the PR but I'm not sure if `cargo install` is valid here because the sqlite db is created on the current working directory. I haven't quite figured out/looked into how to work with this yet.

Screenshot_20221011_143856

**Comment by WaffleMixer** [comment]
If you open it from another directory using the terminal it should prompt you to create another DB. The app won't see the previous DB inside your Finance folder. It doesn't follow a single fixed directory, yet.

**Comment by LemonjamesD** [comment]
I think it has a big memory leak as I am using 96gb of ram

**Comment by WaffleMixer** [comment]
What do you mean? It's consuming 4mb memory here running from the bin.

**Comment by LemonjamesD** [comment]
> What do you mean? It's consuming 4mb memory here running from the bin.

I assume I somehow caused a memory leak because that was the only program I had open and kitty was using 4 cores of my CPU

**Pull request merged**
